services:
  db:
    image: postgres:16
    container_name: helpdesk_db
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk123
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    volumes:
      - helpdesk_pgdata:/var/lib/postgresql/data

volumes:
  helpdesk_pgdata:
